name = "english-dictation-pro"
compatibility_date = "2026-05-03"

[[d1_databases]]
binding = "DB"
database_name = "english-dictation-pro"
database_id = "local-english-dictation-pro"

[assets]
directory = "./"
not_found_handling = "single-page-application"
